server:
  port: 8081

spring:
  application:
    name: ms-curso

  datasource:
    url: jdbc:mysql://localhost:3306/curso_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
